name: Build YADE Exploit

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - name: git checkout
      uses: actions/checkout@v6

    - name: Compile
      run: |
        mkdir -p release
        ./compile.sh 3.00E
        mv build/exploit.iso release/exploit_3.00E_3.00A.iso
        ./compile.sh 3.00U
        mv build/exploit.iso release/exploit_3.00U.iso
        ./compile.sh 3.00J
        mv build/exploit.iso release/exploit_3.00J.iso
        ./compile.sh 3.02E
        mv build/exploit.iso release/exploit_3.02E.iso
        ./compile.sh 3.02C
        mv build/exploit.iso release/exploit_3.02C.iso
        ./compile.sh 3.02D
        mv build/exploit.iso release/exploit_3.02D.iso
        ./compile.sh 3.02G
        mv build/exploit.iso release/exploit_3.02G.iso
        ./compile.sh 3.02J
        mv build/exploit.iso release/exploit_3.02J.iso
        ./compile.sh 3.02K
        mv build/exploit.iso release/exploit_3.02K.iso
        ./compile.sh 3.02U
        mv build/exploit.iso release/exploit_3.02U.iso

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v6
      with:
        name: YADE-exploit-${{ github.sha }}
        path: release/
        if-no-files-found: error
